name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle-validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

  build:
    name: Build app
    runs-on: ubuntu-latest
    needs:
      - gradle-validation

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Setup Gradle Wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build
          if-no-files-found: error

  test:
    name: Execute unit tests
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Setup Gradle Wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test
        run: ./gradlew test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: build/reports/jacoco/test/
          if-no-files-found: error

  codecov:
    name: Publish code coverage to codecov
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: build/reports/jacoco/test/

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # files: build/reports/jacoco/test/html/index.html # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: false # optional (default = false)

  sonarcloud-scan:
    name: Publish metrics to Sonar Cloud
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Setup Gradle Wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: build

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: build/reports/jacoco/test/

      - name: list project files
        run: |
          echo "show current path:"
          pwd
          echo "list current path files:"
          ls -a
          echo "show current path tree:"
          tree

      - name: Publish metrics
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
